name: Node.js CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      NODE_ENV: production
      DATABASE_URL: postgresql://test:test@127.0.0.1:5432/mydb

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION || '20' }}

      - name: Check required secrets and vars
        run: |
          if [ -z "${{ vars.SERVER_DEPLOY_PATH }}" ]; then echo "❌ Missing var: SERVER_DEPLOY_PATH"; exit 1; fi
          if [ -z "${{ secrets.SERVER_HOST }}" ]; then echo "❌ Missing secret: SERVER_HOST"; exit 1; fi
          if [ -z "${{ secrets.SERVER_USER }}" ]; then echo "❌ Missing secret: SERVER_USER"; exit 1; fi
          if [ -z "${{ secrets.SERVER_PASSWORD }}" ]; then echo "❌ Missing secret: SERVER_PASSWORD"; exit 1; fi

          if [ ! -f "ecosystem.config.js" ]; then echo "❌ Missing file: ecosystem.config.js"; exit 1; fi

      - name: Install dependencies
        run: npm ci

      - name: Check if Prisma exists
        id: prisma-check
        run: |
          if [ -f "prisma/schema.prisma" ]; then
            echo "prisma=true" >> $GITHUB_OUTPUT
          else
            echo "prisma=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate Prisma Client (if needed)
        if: steps.prisma-check.outputs.prisma == 'true'
        run: npx prisma generate

      - name: Run Prisma Migrate (if needed)
        if: steps.prisma-check.outputs.prisma == 'true'
        run: npx prisma migrate deploy

      - name: Run Tests
        run: npm test

      - name: Deploy to Server (via SCP)
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: ". , !node_modules"
          target: ${{ vars.SERVER_DEPLOY_PATH }}

      - name: Run SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd ${{ vars.SERVER_DEPLOY_PATH }}
            npm ci --production
            pm2 reload ecosystem.config.js || pm2 start ecosystem.config.js
